# See https://pre-commit.com for more information
# See https://pre-commit.ci for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude_types: [svg, kotlin]
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md,markdown"]
        exclude_types: [svg]
      - id: check-merge-conflict
      - id: check-xml
      - id: mixed-line-ending
        args: [--fix=auto]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.0
    hooks:
      - id: check-github-workflows
